<a href="https://colab.research.google.com/github/pouria1380-creator/Deep_learning_ne/blob/main/pouria_deep_learning_note_one.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch, numpy, matplotlib

In [ ]:
a = 10
print(a)
print(f'torch {a} version: {torch.__version__}')
print(f'check if cude is avaiable {torch.cuda.is_available()}')

10
torch 10 version: 2.8.0+cu126
check if cude is avaiable False


In [ ]:
b = [i**2 for i in range(5)]
print(b)

[0, 1, 4, 9, 16]


In [ ]:
def relu(x):
  return max(0, x)
y = [relu(i) for i in [0,2,3]]
print(y)

[0, 2, 3]


In [ ]:
import numpy as np
matrix = np.array([[3,4],[7,1]])
matrix

array([[3, 4],
       [7, 1]])

In [ ]:
f= np.array([[2,6],[21,9]])
print(f)
print(f'Elementwise multiply {f*matrix}')

[[ 2  6]
 [21  9]]
Elementwise multiply [[  6  24]
 [147   9]]


In [ ]:
#matrix multiply
print(f'Matrix multiply {f@matrix}')

Matrix multiply [[ 48  14]
 [126  93]]


In [ ]:
matrix_2 = np.array([10,30])
matrix_2

array([10, 30])

In [ ]:
print(matrix+matrix_2)

[[13 34]
 [17 31]]


compute w=ax+b with MSE loss

Define x, W and b

write the formula

Define target value

Calculate loss and print

x = [1 2], W = [2 , b = 1 3]



In [ ]:
import numpy as np
x= np.array([1,2])
w = np.array([[2],[3]])
b=np.array([1])
print(f'x: {x}')
print(f'w: {w}')
print(f'b: {b}')

x: [1 2]
w: [[2]
 [3]]
b: [1]


In [ ]:
y = x @ w +b
target = 10
print(f'y: {y}')
print(f'target: {target}')

y: [9]
target: 10


In [ ]:
loss_function = np.mean((y-target)**2)
print(f'loss: {loss_function}')

loss: 1.0


Torch

In [35]:
x = torch.tensor([[1.0,2.0]],requires_grad= True)
w = torch.tensor([[2.0],[3.0]], requires_grad=True)
b=torch.tensor([1.0], requires_grad=True)
print(f'x: {x}')
print(f'w: {w}')
print(f'b: {b}')
y = x @ w +b
print(f'y: {y}')
y.backward()
print(f'dy/dw:{w.grad}')
print(f'dy/db:{b.grad}')


x: tensor([[1., 2.]], requires_grad=True)
w: tensor([[2.],
        [3.]], requires_grad=True)
b: tensor([1.], requires_grad=True)
y: tensor([[9.]], grad_fn=<AddBackward0>)
dy/dw:tensor([[1.],
        [2.]])
dy/db:tensor([1.])
