<a href="https://colab.research.google.com/github/pouria1380-creator/Deep_learning_ne/blob/main/torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.empty(2,3)
print(x)

tensor([[5.5621e-07, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


In [ ]:
x = torch.rand(2,2,2,3)
print(x)

tensor([[[[0.3717, 0.2094, 0.2732],
          [0.0715, 0.3916, 0.2161]],

         [[0.4371, 0.2645, 0.1349],
          [0.4202, 0.5961, 0.6297]]],


        [[[0.6559, 0.7729, 0.8510],
          [0.6625, 0.6767, 0.3956]],

         [[0.9760, 0.8462, 0.5550],
          [0.4091, 0.8284, 0.4963]]]])


In [ ]:
#tensor with random values
x= torch.rand(2,2)
x

tensor([[0.8495, 0.9489],
        [0.2468, 0.4346]])

In [ ]:
 #tensor with zeros
 x= torch.zeros(2,2)
 x

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
#tensor with ones
x= torch.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
print(x.dtype)

torch.float32


In [ ]:
x= torch.ones(2,2,dtype=torch.int)
print(x.dtype)

torch.int32


In [ ]:
x = torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [ ]:
#look at the size
x.size()

torch.Size([2])

In [ ]:
x= torch.tensor([2.5,0.1])
x

tensor([2.5000, 0.1000])

In [ ]:
x= torch.rand(2,2)
y= torch.rand(2,2)
print(x)
print(y)

tensor([[0.9320, 0.0729],
        [0.3780, 0.8009]])
tensor([[0.1971, 0.7239],
        [0.3985, 0.7659]])


In [ ]:
z = x+y
z

tensor([[1.1291, 0.7969],
        [0.7765, 1.5668]])

In [ ]:
z = torch.add(x,y)
z

tensor([[1.1291, 0.7969],
        [0.7765, 1.5668]])

In [ ]:
y.add_(x)
print(y)

tensor([[1.1291, 0.7969],
        [0.7765, 1.5668]])


In [ ]:
z=x-y

In [ ]:
z

tensor([[-0.1971, -0.7239],
        [-0.3985, -0.7659]])

In [ ]:
mt1 = torch.tensor([[2,2],[3,4]])
mt1

tensor([[2, 2],
        [3, 4]])

In [ ]:
mt2 = torch.tensor([[1,3],[78,1]])
mt2

tensor([[ 1,  3],
        [78,  1]])

In [ ]:
print(mt1[:,0])

tensor([2, 3])


In [ ]:
mt1@mt2

tensor([[158,   8],
        [315,  13]])

In [ ]:
mt3 = torch.rand(4,4)
mt3

tensor([[0.0071, 0.8683, 0.5624, 0.1259],
        [0.6189, 0.3094, 0.7439, 0.0850],
        [0.5197, 0.4663, 0.3049, 0.0236],
        [0.1594, 0.5379, 0.5792, 0.7013]])

In [ ]:
mt4 = mt3.view(16)
mt4

tensor([0.0071, 0.8683, 0.5624, 0.1259, 0.6189, 0.3094, 0.7439, 0.0850, 0.5197,
        0.4663, 0.3049, 0.0236, 0.1594, 0.5379, 0.5792, 0.7013])

In [ ]:
mt5 = mt3.view(-1,8)
mt5

tensor([[0.0071, 0.8683, 0.5624, 0.1259, 0.6189, 0.3094, 0.7439, 0.0850],
        [0.5197, 0.4663, 0.3049, 0.0236, 0.1594, 0.5379, 0.5792, 0.7013]])

In [ ]:
print(mt5.size())

torch.Size([2, 8])


In [ ]:
import numpy as np
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [ ]:
b= a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
  a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [ ]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [ ]:
a= np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [ ]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [ ]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5,device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x+y



tensor([[-0.1971, -0.7239],
        [-0.3985, -0.7659]])

calculate gradient with autograd

In [ ]:
import torch
x = torch.randn(3,requires_grad=True)
x


tensor([-1.1449,  0.2454,  1.3405], requires_grad=True)

In [ ]:
y = x+2
y

tensor([0.8551, 2.2454, 3.3405], grad_fn=<AddBackward0>)

In [ ]:
z = y*y*2
z

tensor([ 1.4625, 10.0838, 22.3184], grad_fn=<MulBackward0>)

In [ ]:
z = torch.mean(z)
z

tensor(11.2882, grad_fn=<MeanBackward0>)